// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvtlgXaf0HuHbGMWxS6t9J9IbG69BRd1I',
    appId: '1:747125665836:web:4e542c9dbc35d021716189',
    messagingSenderId: '747125665836',
    projectId: 'fir-authentication-99a13',
    authDomain: 'fir-authentication-99a13.firebaseapp.com',
    storageBucket: 'fir-authentication-99a13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbn68ojjAdQ8XlfPEGsyrfdKQjUInKaGs',
    appId: '1:747125665836:android:92839f4dccd6f173716189',
    messagingSenderId: '747125665836',
    projectId: 'fir-authentication-99a13',
    storageBucket: 'fir-authentication-99a13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKb0NRTAJhUOALvjCqg5X-7-Zl7fqHmVA',
    appId: '1:747125665836:ios:f4f26f610ce0cff5716189',
    messagingSenderId: '747125665836',
    projectId: 'fir-authentication-99a13',
    storageBucket: 'fir-authentication-99a13.appspot.com',
    iosClientId: '747125665836-0pmjrphob2g7esvb83eoalrqsblemrpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.news1stApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKb0NRTAJhUOALvjCqg5X-7-Zl7fqHmVA',
    appId: '1:747125665836:ios:f4f26f610ce0cff5716189',
    messagingSenderId: '747125665836',
    projectId: 'fir-authentication-99a13',
    storageBucket: 'fir-authentication-99a13.appspot.com',
    iosClientId: '747125665836-0pmjrphob2g7esvb83eoalrqsblemrpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.news1stApp',
  );
}
